#! /bin/sh

bspc monitor -d 1 2 3 4 5

bspc config border_width         3
bspc config active_border_color \#FFFFFF
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

# fix java issues
wmname LG3D

xsetroot -cursor_name left_ptr &

/usr/libexec/gsd-xsettings & 
/usr/bin/gnome-keyring-daemon --start --components=secrets &
/usr/lib/policykit-1-gnome/polkit-gnome-authentication-agent-1 & 
~/.config/i3/i3-battery-popup/i3-battery-popup -n -D -L 20 -l 10 &

~/.config/polybar/launch.sh --material &
# ~/.config/polybar/material/scripts/pywal.sh ~/Pictures/Wallpapers/bg-0114.png & 
picom --config ~/.config/picom/picom.conf &
feh --bg-fill ~/Pictures/Wallpapers/bg-0143.png &

dunst &
flameshot & 
nm-applet &
blueman-applet &
pgrep -x sxhkd > /dev/null || sleep 1; sxhkd &

