#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 1 2 3 4 5 6 7 8 9 10

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

# fix java issues
wmname LG3D

/usr/libexec/gsd-xsettings & 
/usr/bin/gnome-keyring-daemon --start --components=secrets &
/home/nandafirmans/.config/i3/i3-battery-popup/i3-battery-popup -n -D -L 20 -l 10 &

/home/nandafirmans/.config/polybar/launch.sh --cuts &
/home/nandafirmans/.config/polybar/cuts/scripts/pywal.sh /home/nandafirmans/Pictures/Wallpapers/background.png & 
picom --config /home/nandafirmans/.config/picom/picom.conf &
feh --bg-fill /home/nandafirmans/Pictures/Wallpapers/background.png &

flameshot & 
nm-applet &
blueberry-tray &
# skypeforlinux & 

