#!/bin/sh

yabai -m config layout bsp

yabai -m config window_placement second_child
yabai -m config external_bar all:38:0

# padding 
yabai -m config top_padding 8
yabai -m config bottom_padding 8
yabai -m config left_padding 8
yabai -m config right_padding 8
yabai -m config window_gap 8

# center mouse on window with focus
yabai -m config mouse_follows_focus on
# yabai -m config mouse_follows_focus off
yabai -m config focus_follows_mouse autofocus

# modifier for clicking and dragging with mouse
yabai -m config mouse_modifier ctrl

# set modifier + left-click drag to move window
yabai -m config mouse_action1 move

# set modifier + right-click drag to resize window
yabai -m config mouse_action2 resize

# when window is dropped in center of another window, swap them (on edges it will split it)
yabai -m mouse_drop_action stack

# disable specific apps
yabai -m rule --add title="" manage=off
yabai -m rule --add app="^System Settings$" manage=off
yabai -m rule --add app="^Calculator$" manage=off
yabai -m rule --add app="^Karabiner-Elements$" manage=off
yabai -m rule --add app="^Raycast$" manage=off
yabai -m rule --add app="^Finder$" manage=off
yabai -m rule --add app="^Vanilla$" manage=off
yabai -m rule --add app="^Flameshot$" manage=off
yabai -m rule --add app="^Preview$" manage=off
yabai -m rule --add app="^Activity Monitor$" manage=off

# S K E T C H Y B A R  E V E N T S
yabai -m signal --add event=window_focused action="sketchybar -m --trigger window_focus &> /dev/null"
yabai -m signal --add event=window_title_changed action="sketchybar -m --trigger title_change &> /dev/null"
